# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm" # Specify npm for Node.js projects (Express, Prisma)
    directory: "/" # Location of package.json and lock file (relative to repo root)
    schedule:
      interval: "weekly" # Check for updates once a week
    # OPTIONAL: Add labels to Dependabot PRs
    labels:
      - "dependencies"
      - "dependabot"
    # OPTIONAL: Assign reviewers to Dependabot PRs
    reviewers:
      - "nisaacdz"
      - "ziglaCity"
      - "steveAzo"
    # OPTIONAL: Limit the number of open PRs from Dependabot for npm
    open-pull-requests-limit: 10
    # OPTIONAL: Customize commit messages
    commit-message:
      prefix: "chore" # Prefix commit messages with "chore"
      include: "scope" # Include the scope (e.g., "deps", "devDeps")
