version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'dependabot'
    reviewers:
      - 'nisaacdz'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore'
      include: 'scope'
