version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'dependabot'
    reviewers:
      - "nisaacdz"
    # OPTIONAL: Limit the number of open PRs from Dependabot for npm
    open-pull-requests-limit: 2
    # OPTIONAL: Customize commit messages
    commit-message:
      prefix: 'chore'
      include: 'scope'
