# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - production # CHANGED: Now triggers on your production branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build # CHANGED: Step name updated for clarity
        run: |
          npm install
          npm run build --if-present
          # REMOVED: "npm run test --if-present" is no longer here

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4275FE4F1124138A93B1CA1D68B3B7A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6AF4DA3CF314F7AAB93C544D18DC2E9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D44FAB8E3D444961AAC54F8BFCE19A63 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sl-core'
          slot-name: 'Production'
          package: .
